### ISSUE TITLE
Fixes for schema fields on Organization, Dataset and Resource pages

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#1]
Currently, we have enabled ckanext-fluent extension to provide multilingual support while submitting forms for creating and editing organizations, datasets and resources.

## Acceptance

* [x] The pages show only En and Ar fields instead of three fields
* [x] Form pushes en title as main title in dataset create page
* [x] Form pushes the english keywords as tags during dataset creation
* [x] The resource page name (en) is generated when file is uploaded (As the default behaviour is)
* [x] The URL for organization, dataset and resource is autogenerated based on the en field.
* [x] All the Arabic text fields are working R -> L

## Tasks
* [x] Dataset page `Title` fixes
  * [x] **[Ismail]** We need to get rid of the main title field and display the eng tile as the main title
  * [x] **[Tanvir]** Generate the url according to the EN Title field
    ![](https://i.imgur.com/mNqLWQr.png)
* [x] **[Sagar]** Fix fields length for all the translated fields (Match it with the default core field lengths)
* [x] **[Tanvir]** Convert text fields for Arabic should be R -> L
* [x] **[Sagar]** Keywords
  * [x] We are using keywords instead of tags in the scheming yaml
  * [x] We push the English keywords to the tags too when the form is submitted
  * [x] Push main `description` (notes) to be pushed as translated english notes as currently they are null
    ![Screenshot from 2022-02-07 21-36-54](https://user-images.githubusercontent.com/57398621/152831308-ba38ee3e-0cec-4dd3-a563-a1603f23cc37.png)
* [x] **[Ismail]** Enable Bilingual support for author and maintainer field on dataset page
* [x] **[Ismail]** Enable Bilingual support for org and group pages
  * Fixed by Sagar's commit 
* [x] **[Ismail]** Test Everything

## Testing

Test all the conditions mentioned in the `Acceptance` section
* Dataset: https://ckan.fcsc.develop.datopian.com/dataset/final-test-bilingual
* Organization: https://ckan.fcsc.develop.datopian.com/organization/test-organization-bilingual-english
* Group: https://ckan.fcsc.develop.datopian.com/group/test-group-english

### Results
* **Package show**
  ```json
  {"help": "https://ckan.fcsc.develop.datopian.com/api/3/action/help_show?name=package_show", "success": true, "result": {"author": "English Author", "author_email": "test@email.com", "author_translated": {"ar": "Arabic Author", "en": "English Author"}, "creator_user_id": "9035459a-cfbd-4d35-b0c9-82bb156c2bb1", "id": "41d6b15b-3702-4c2d-b797-a6a2484e6cad", "isopen": false, "keywords": {"ar": ["\u0627\u0644\u0632\u0631\u0627\u0639\u0629"], "en": ["Agriculture"]}, "license_id": "notspecified", "license_title": "License not specified", "maintainer": "English Maintainer", "maintainer_email": "test@email.com", "maintainer_translated": {"ar": "Arabic Maintainer", "en": "English Maintainer"}, "metadata_created": "2022-02-08T11:43:23.499821", "metadata_modified": "2022-02-08T11:44:08.829541", "name": "final-test-bilingual", "notes": "", "notes_translated": {"ar": "Arabic Description", "en": "English Description"}, "num_resources": 1, "num_tags": 0, "organization": {"id": "5555c061-6f00-456c-88db-1f809740cd26", "name": "test-organization", "title": "1st Test Organization", "type": "organization", "description": "Test Organization for initial setup", "image_url": "https://ckan.fcsc.develop.datopian.com/uploads/group/2022-01-31-195844.368141-datopian.png", "created": "2022-01-27T17:08:44.653880", "is_organization": true, "approval_status": "approved", "state": "active"}, "owner_org": "5555c061-6f00-456c-88db-1f809740cd26", "private": false, "state": "active", "title": "Final Test Bilingual", "title_translated": {"ar": "Final Test Bilingual Arabic Title", "en": "Final Test Bilingual"}, "type": "dataset", "url": "http://example/data.json", "version": "1.0", "resources": [{"cache_last_updated": null, "cache_url": null, "created": "2022-02-08T11:44:08.235186", "datastore_active": true, "description": null, "format": "CSV", "hash": "", "id": "e88da843-1c6e-4392-9fe3-9b5f3636ddfd", "last_modified": null, "metadata_modified": "2022-02-08T11:44:08.851994", "mimetype": null, "mimetype_inner": null, "name": "Sheep By Emirate Age and Gender", "name_translated": {"ar": "Arabic Name", "en": "Sheep By Emirate Age and Gender"}, "notes_translated": {"ar": "Arabic Description", "en": "English Description"}, "package_id": "41d6b15b-3702-4c2d-b797-a6a2484e6cad", "position": 0, "resource_type": null, "size": null, "state": "active", "url": "https://ckan.fcsc.develop.datopian.com/dataset/41d6b15b-3702-4c2d-b797-a6a2484e6cad/resource/e88da843-1c6e-4392-9fe3-9b5f3636ddfd/download/sheep-by-emirate-gender-age-2014-2017.csv", "url_type": "upload"}], "tags": [], "groups": [], "relationships_as_subject": [], "relationships_as_object": []}}
  ```
* **Resource show**
  ```
  {"help": "https://ckan.fcsc.develop.datopian.com/api/3/action/help_show?name=resource_show", "success": true, "result": {"cache_last_updated": null, "cache_url": null, "created": "2022-02-08T11:44:08.235186", "datastore_active": true, "description": null, "format": "CSV", "hash": "", "id": "e88da843-1c6e-4392-9fe3-9b5f3636ddfd", "last_modified": null, "metadata_modified": "2022-02-08T11:44:08.851994", "mimetype": null, "mimetype_inner": null, "name": "Sheep By Emirate Age and Gender", "name_translated": {"ar": "Arabic Name", "en": "Sheep By Emirate Age and Gender"}, "notes_translated": {"ar": "Arabic Description", "en": "English Description"}, "package_id": "41d6b15b-3702-4c2d-b797-a6a2484e6cad", "position": 0, "resource_type": null, "size": null, "state": "active", "url": "https://ckan.fcsc.develop.datopian.com/dataset/41d6b15b-3702-4c2d-b797-a6a2484e6cad/resource/e88da843-1c6e-4392-9fe3-9b5f3636ddfd/download/sheep-by-emirate-gender-age-2014-2017.csv", "url_type": "upload"}}
  ```
* **Organization show**
  ```
  {"help": "https://ckan.fcsc.develop.datopian.com/api/3/action/help_show?name=organization_show", "success": true, "result": {"approval_status": "approved", "created": "2022-02-08T11:53:32.071281", "description": "", "display_name": "test-organization-bilingual-english", "id": "09723c96-ad24-465a-a08c-6e0bb25ba397", "image_display_url": "https://ckan.fcsc.develop.datopian.com/uploads/group/2022-02-08-115331.979623-datopian.png", "image_url": "https://ckan.fcsc.develop.datopian.com/uploads/group/2022-02-08-115331.979623-datopian.png", "is_organization": true, "name": "test-organization-bilingual-english", "notes_translated": {"ar": "Test Organization Bilingual Arabic Descr", "en": "Test Organization Bilingual English Descr"}, "num_followers": 0, "package_count": 0, "state": "active", "title": "Test Organization Bilingual English", "title_translated": {"ar": "Test Organization Bilingual Arabic", "en": "Test Organization Bilingual English"}, "type": "organization", "users": [{"about": null, "activity_streams_email_notifications": false, "capacity": "admin", "created": "2022-01-27T15:19:02.718942", "display_name": "ckan_admin", "email_hash": "4b1f5baa085919a730564267182fbdb7", "fullname": null, "id": "9035459a-cfbd-4d35-b0c9-82bb156c2bb1", "image_display_url": null, "image_url": null, "name": "ckan_admin", "number_created_packages": 3, "state": "active", "sysadmin": true}], "tags": [], "groups": []}}
  ```
* **Group show**
  ```
  {"help": "https://ckan.fcsc.develop.datopian.com/api/3/action/help_show?name=group_show", "success": true, "result": {"approval_status": "approved", "created": "2022-02-08T12:00:26.398319", "description": "", "description_translated": {"ar": "Test Group Arabic", "en": "Test Group English"}, "display_name": "test-group-english", "id": "fbc0d95a-a492-425a-95a6-b735de66af41", "image_display_url": "https://ckan.fcsc.develop.datopian.com/uploads/group/2022-02-08-120026.243059-datopian.png", "image_url": "https://ckan.fcsc.develop.datopian.com/uploads/group/2022-02-08-120026.243059-datopian.png", "is_organization": false, "name": "test-group-english", "num_followers": 0, "package_count": 0, "state": "active", "title": "Test Group English", "title_translated": {"ar": "Test Group Arabic", "en": "Test Group English"}, "type": "group", "users": [{"about": null, "activity_streams_email_notifications": false, "capacity": "admin", "created": "2022-01-27T15:19:02.718942", "display_name": "ckan_admin", "email_hash": "4b1f5baa085919a730564267182fbdb7", "fullname": null, "id": "9035459a-cfbd-4d35-b0c9-82bb156c2bb1", "image_display_url": null, "image_url": null, "name": "ckan_admin", "number_created_packages": 3, "state": "active", "sysadmin": true}], "tags": [], "groups": []}}
  ```
* Default description for `resource`, `organization` and `group` is null (Not sure if we need a fix for that for now
* Tag is not being added to the `tag` key of the data dictionary. I see only keywords for now, no tags in the package_show. Need to check that.
Tracking default description issue over here --> https://github.com/FCSCOpendata/ckanext-fcscopendata/issues/7
