### ISSUE TITLE
Enable Tag Vocabularies for the fcsc ODP

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#10]
We need to develop and enable the tag vocabularies feature so that we can have related tags grouped together into custom fields.

## Example to implement
- Economy [Group and Vocabulary]
  - Tourism [tag]
  - Money and Banking [tag]
  - Foreign Investment [tag]
 
- Education  [Group and Vocabulary]
  - Education Outcome [tag]
  - Education Facilities [tag]

## Acceptance

* [ ] Tag vocabularies are present in the opendata platform

## Tasks

* [x] Go through the [docs](https://docs.ckan.org/en/2.9/maintaining/tag-vocabularies.html)
* [ ] Develop/enable the feature in this extension
* [ ] Test the functionality

## Analysis

The link to the docs ==> https://docs.ckan.org/en/2.9/maintaining/tag-vocabularies.html

**Comment by osahon-okungbowa** [comment]
waiting for client meeting to decide if this is something to develop and use further

**Comment by osahon-okungbowa** [comment]
closing this issue.

Features have been implemented through another issue
