### ISSUE TITLE
Hierarchy template update for bilingual  fields.

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#11]
## Acceptance criteria 
* [ ]  I can see both organization and group about page info is formatted and displays the values of the field in selected languages. 

## Tasks 
* [x]  Update template and format about info for organization and group page. 
      -  https://ckan.fcsc.develop.datopian.com/group/about/test-group-english
      -  https://ckan.fcsc.develop.datopian.com/organization/about/test-organisation-4
      <img width="1054" alt="Screen Shot 2022-02-14 at 6 50 56 PM" src="https://user-images.githubusercontent.com/87696933/153869688-4ab1322d-78ed-4fd2-9b65-87ec396224e8.png">
* [ ] Test/ Deploy to dev env.

**Comment by sagargg** [comment]
@osahon-okungbowa  this is done.  Please review the fix.

**Comment by osahon-okungbowa** [comment]
@sagargg confirmed as fixed
