### ISSUE TITLE
Enable Bilingual search

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-fcscopendata#17]
We want Package search to return appropriate search results whenever the search keyword is non-English word

## Acceptance 
- [x] Ensure search field and `package_search` API works with non-English word

## Todos
- [x] Don analysis to see why current package_search is not working with non English word
- [x] Fix issue based on the analysis

## Analysis
Based on our investigation, we find out the issue is based on the Unicode representation of the search keyword, the validator ensures all characters are ASCII valid.
