### ISSUE TITLE
Analysis on fluent bilingual  support for vocabulary and tags.

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#19]
## Acceptance Criteria 
* [ ] I have an analysis of how the bilingual can be implemented on vocabulary.
* [ ] I can see the vocabulary also support bilingual (eng and Arabic). 

## Tasks 
* [x] Analaysis and review 
* [x] Implement on analysis done
* [ ] Test/Deploy 

## Analysis 
The fluent extension doesn't support bilingual on tags and vocabulary.   Fluent actually stores the translation info into the extra fields like [package extras](https://github.com/ckan/ckan/blob/master/ckan/model/package_extra.py#L17-L24), [group extras](https://github.com/ckan/ckan/blob/master/ckan/model/group_extra.py#L17-L23).

this is how fluent stores translated fields values for packages in the `package_extra` table and it is similar for groups. 
<img width="1160" alt="Screen Shot 2022-02-26 at 9 57 53 AM" src="https://user-images.githubusercontent.com/87696933/155828446-05a85b50-4b04-4967-8ffe-b80f68f7b0ea.png">

CKAN doesn't have extra fields for vocabulary and tags So the question is **where it will be stored?** 
&nbsp;&nbsp; we can create extra tables eg. `tag_extras` and `vocabulary_extras` on the forked fluent extension. 

**Implementation Approach** 
1. Create extra tables for both vocabulary and tags in order to store bilingual text. 
2. Override `vocabulary_create` API action using toolchain function so that it also stores the translated text on extra db tables. 
**pseudo code** 
  ``` python 
  def vocabulary_create(up_func,context,data_dict):

      name_translated = {
          'en' : data_dict.get('name_translated-en', data_dict['name']), 
          'ar': data_dict.get('name_translated-ar', '')
      }
      data_dict["extras"] = [{"key": "author_translated", 
          "value": json.dumps(name_translated, ensure_ascii=False)
          }]
      result = up_func(context, data_dict)  

        # save translated fields value to extras 
      extras_save(data_dict["extras"], vocabulary.modal, context)
      return result
  
  ```
  **pseudo code** 

3. Similar override `tag_create` API action using toolchain function.
  ``` python 
  def tag_create(up_func, context,data_dict):
      name_translated = {
          'en' : data_dict.get('name_translated-en', data_dict['name']), 
          'ar': data_dict.get('name_translated-ar', '')
      }
      data_dict["extras"] = [{"key": "author_translated", 
          "value": json.dumps(name_translated, ensure_ascii=False)
          }]
      result = up_func(context, data_dict)  

        # save translated fields value to extras 
      extras_save(data_dict["extras"], tag.modal, context)
      return result
      
```
4. override `tag_show` and `vocabulary _show` to implement extras translated fields into the return result.

**Comment by osahon-okungbowa** [comment]
@sagargg question: is there a way that the languages to be supported by the vocabulary and tags can be specified by a schema? or must it be hardcoded to only EN and AR
