### ISSUE TITLE
Create UI for Vocabulary and Tags

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-fcscopendata#20]
We want to have ui where sysadmin can easily create and manage vocabularies and their tags.

## Acceptance

- [ ] Have a page to display all vocabularies
- [ ] Have a page to display vocabulary and its tags
- [ ] Have a page to create vocabulary and its tags
- [ ] Have a page to manage vocabulary and its tags
 
## Task

- [ ] implement vocabulary index page to display all vocabularies
- [ ] implement vocabulary page to display vocabulary name and it tags
- [ ] implement a page to create vocabulary and its tags
- [ ] implement a page to edit vocabulary and delete vocabulary
- [ ] implement a page to edit or delete a tag

**Comment by steveoni** [comment]
Here is the repo for this issue: https://github.com/datopian/ckanext-vocabulary

**Comment by sagargg** [comment]
We need to display the error flash message when there is a validation error.  @steveoni  @osahon-okungbowa 

<img width="1440" alt="Screen Shot 2022-03-03 at 9 00 36 AM" src="https://user-images.githubusercontent.com/87696933/156489368-080b9b98-faab-4501-a16d-032faf668508.png">

**Comment by osahon-okungbowa** [comment]
i agree. assigning to @steveoni
