### ISSUE TITLE
 Create API to get list of datasets per vocabulary

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#22]
## Acceptance Criteria 
- [ ]  I have an API that returns a list of datasets when I query with vocabulary id or name. 

## Tasks 
- [x] Aanalysis 
- [x] Implement 
- [ ] Test locally  and raise PR
- [ ] Review and deploy to dev env.

**Comment by sagargg** [comment]
There is already API for dataset search per vocabulary.

1. Search the dataset by specific vocabulary.
`http://localhost:5000/api/action/package_search?fq=vocab_Indicator:*`
 Provided a vocab name with the prefix  `vocab_` and `*` chars as tags. 

2. Search the dataset by specific vocabulary tag.
`http://localhost:5000/api/action/package_search?fq=vocab_Indicator:GDP` 
It returns list of datasets using tag ‘GDP’ from vocabulary ‘Indicator’:

**Comment by sagargg** [comment]
It will also work on UI search bar. 

<img width="926" alt="Screen Shot 2022-03-06 at 9 57 36 AM" src="https://user-images.githubusercontent.com/87696933/156908900-162e11b9-8e34-4b00-bc26-cc306e4348d2.png">

**Comment by osahon-okungbowa** [comment]
@sagargg some questions:
- can i search for more than one vocabulary at a time using this package_search API?
- can I search for multiple tags from a vocabulary
- what if the vocabulary has a space e.g. `Birth Rate`, how would I write this using the API?
- is this package_search API documented somewhere in the repo? if so, where?

**Comment by sagargg** [comment]
@osahon-okungbowa  the package search allows advance SLOR querying. 
1. can i search for more than one vocabulary at a time using this package_search API?
Yes,  You need to add `or`  in between two vocab queries eg. `package_search?fq=(vocab_Industry:*  OR vocab_Indicator:*)`

2. can I search for multiple tags from a vocabulary
yes, it is similar to tags,  `package_search?fq=(vocab_Industry: "Tag 1" "Tag2")`.

3. what if the vocabulary has a space e.g. Birth Rate, how would I write this using the API?
yes, it should have double quotes,  `package_search?fq=(vocab_Industry: "Tag space1" "Tag space2")`.  

4. is this package_search API documented somewhere in the repo? if so, where?
yes, it is documented somewhat here.
http://docs.ckan.org/en/2.9/api/#tag-vocabularies

**Comment by osahon-okungbowa** [comment]
COMMENTS ABOVE MAY BE USEFUL FOR FUTURE REFERENCE

**Comment by sagargg** [comment]
**Not Needed**
