### ISSUE TITLE
Bilingual query support on tags facet on datasets page. 

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#23]
## Acceptance Criteria
- [ ]   TODO 

## Tasks 
- [ ] Analysis and Implement 
- [ ] Test and raise PR
- [ ] Review and deploy to dev environment.

**Comment by osahon-okungbowa** [comment]
@sagargg please we need this feature to work via API for the frontend.

For example in the frontend we send facet queries to search for datasets by tags. We need to test and make sure this will work for Arabic tags.

@MuhammadIsmailShahzad if needed, please support with basic arabic translations for some tags in our dev ckan e.g. "missing years" tag
