### ISSUE TITLE
[Epic][Bugs] Translated pages not working as intended

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#31]
There are a couple of bugs showing when we switch to Arabic translated version of the site.

## Acceptance

* [ ] The translated pages are rendering fine without any bugs
* [ ] Translated text on pages

## Tasks

* [ ] [Fix width of the pages](https://github.com/FCSCOpendata/ckanext-fcscopendata/issues/30)
* [ ] [Show translated text on pages](https://github.com/FCSCOpendata/ckanext-fcscopendata/issues/26)

**Comment by sagargg** [comment]
Checked, translation broke after this commit https://github.com/FCSCOpendata/ckanext-fcscopendata/commit/badeb0f64b39c83f1d70735d69d68b429cfb53c4.
