### ISSUE TITLE
Add Start and End Period field to Dataset form

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-fcscopendata#38]
We want to add start and end period fields in the following format Month-Year to Dataset create and edit page

## Acceptance
- [ ] Ensure Start and End Period field is present in Dataset form
- [ ] Start and End Period Field are DatePicker field
- [ ] Start and End Period Field are present in the `package_search` result

## Task
- [ ] Add Start and Ed period to Dataset schema
- [ ] Update action function for package
- [ ] update dataset form UI in create and edit page
- [ ] Add Date Picker to Start and End period field

**Comment by sagargg** [comment]
Stephen and i had a sync and tested the current implementation, looks like it is already working as expected. @steveoni  will do more tests and provide the example in this thread. cc @osahon-okungbowa 

If it didn't work, we may have to follow this approach. 
1.  Add a new Solr schema field as the data type for the start and end dates. 
2. Map the form params store that date values to the newly created date type Solr field.  (reindex every time when metadata updates)
3. do an analysis of how SOLR search with two date fields 
   maybe :
    -  `q=start_date_field:[start_date_value TO  end_date _value] AND end_date _value:[start_date_value TO  end_date _value]`
    this may be useful https://stackoverflow.com/questions/17648021/solr-multivalued-date-range-from-two-separate-field-as-sub-entity

**Comment by sagargg** [comment]
@steveoni  @steveoni   Also, I've noticed date picker UI  only allows to pick year and month but i think users will try to pick days also. Maybe we should display not allowed cursor when the user tries to hover day in the calendar, just to avoid that confusion and they know it is not allowed.
