### ISSUE TITLE
Add image input field to all groups type(organisation and themes).

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#39]
## Acceptance  Criteria    
* [x] I can see the image input field is added into all groups (organization and themes) and able to update the SVG image. 

## Tasks
* [x] Add image update a preset field in the scheming YAML file. 
* [x] Modify templates to render/display the uploaded  image (SVG) somewhere close to organizaiton image. 
* [x] Review/ Deploy

**Comment by sagargg** [comment]
**Done and deployed** to dev env.
