### ISSUE TITLE
clean up the current FCSC dev portal theme

### ISSUE THREAD

**Issue by osahon-okungbowa** [FCSCOpendata/ckanext-fcscopendata#4]
## Description
As a portal user, i want the current FCSC Dev portal to look tidy and clean, so that it is presentable **and** the same theme can easily be ported to other FCSC instances with minimal or no work

## Todos/Tasks
- [x] have the Bayanat logo as part of the FCSC theme
- [x] the hero text on the home page should read "Welcome to UAE Open Data"
- [x] remove "About Datopian" link from the footer
- [x] change every occurrence of "Group(s)" to "Theme(s)". This should be done in such a way that allows CKAN to translate "Theme(s)" to Arabic in future work.
- [ ] update the fav icon to the Bayanat logo (bonus)

## Acceptance Criteria
- [ ] all tasks have been completed
- [ ] all tasks have been successfully deployed and the FCSC dev portal is running successfully with the updates in place
