### ISSUE TITLE
Add additional  description, default image and icon upload input filed  in Categories. 

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#40]
## Acceptance Criteria 
* [ ]  I can see the additional text area filed (description) field is added in categories. 
* [ ] I can see the Image and icon upload input filed anded and able to upload the image files. 

## Tasks 
* [x] Implement adding additonal input fileds (description, default image, iocn image). 
* [x] Test/Review
* [x] Deploy to dev env.

**Comment by sagargg** [comment]
Done and deployed to dev env.  cc @osahon-okungbowa

**Comment by osahon-okungbowa** [comment]
@sagargg well done.

However, one feedback:

- there is no place where the image or icon of a Category is displayed.
Can we display the image and ion for a Category on the Category Details page? Where we have the category title displayed e.g. https://ckan.fcsc.develop.datopian.com/vocabulary/41bba22d-4c2b-430d-98a1-3520803eb7e9/read ?

We can sync on this if you need ore guidance

**Comment by sagargg** [comment]
@osahon-okungbowa  now image and icon will be displayed at left sidebar similar to groups page. 
https://ckan.fcsc.develop.datopian.com/vocabulary/41bba22d-4c2b-430d-98a1-3520803eb7e9/read

**Comment by sagargg** [comment]
@osahon-okungbowa Added category description with this PR https://github.com/FCSCOpendata/ckanext-vocabulary/pull/10

**Comment by sagargg** [comment]
**DONE**
