### ISSUE TITLE
Install openess rating extension

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#41]
## Acceptance Criteria 
* [x] I see the openness rating  extension is installed in dev env. 

## Tasks 
* [x] Evaluate available openness rating extension by installing locally.
    * https://github.com/ckan/ckanext-qa
    * https://github.com/derilinx/ckanext-dietstars 
 * [x] Raise PR updating dx configuration to install openness rating extension.
 * [x]  Review/Deploy

**Comment by sagargg** [comment]
**Done and deployed** to the dev. 
In package search API, the openness score is returned as `qa`  property.  cc @osahon-okungbowa 
<img width="1266" alt="Screen Shot 2022-04-19 at 10 09 19 AM" src="https://user-images.githubusercontent.com/87696933/163919798-1a669d94-4b10-4d6a-9cb1-c988ea9f6394.png">

**Comment by sagargg** [comment]
**DONE**
