### ISSUE TITLE
Add Resource Download Stats

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-fcscopendata#45]
## Acceptance

- [ ] Resource Download stats is visible in Dataset Pages
- [ ] Resource Download stats are included in package_search API

## Task

- [ ] install `google-analytics1 and enable resource download tracking
- [ ] Analysis of extension to enable visibility of download stats in Dataset Page and  package_search
- [ ] Install the provided extension
