### ISSUE TITLE
Enable db backups for fcsc

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#58]
Currently, there are no periodic backups for DB(s) of fcsc instances.

## Acceptance

* [ ] Backups are enabled and uploading to cloud

## Tasks

* [ ] Investigate setting up backups
* [ ] Implement and test
