### ISSUE TITLE
Fix Package themes bug

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-fcscopendata#59]
We want to ensure  Themes (and subthemes) for packages are correctly displayed.

## Acceptance

- [ ] Subthemes for packages should be highlighted in the main Themes hierarchy tree

## Task
- [ ] create helper function to enable correct higlighting
- [ ] update group_list templates
