### ISSUE TITLE
Editor user not allowed to change private metadata on UI.

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#69]
##  Acceptance Criteria 
* [ ]  I can see that the editor user is not allowed to change private metadata to public or TURE on UI  and it's selected as private by default.  

## Tasks
* [x]  Implement in code base.
* [ ] Test/Review/Deploy
