### ISSUE TITLE
fix metadata bugs for Organisations, Groups and Resources

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#7]
There are a couple of bugs with our metadata since we enabled bilingual support. We need the bugs fixed.
Bugs are listed below

## Bugs
1. Whenever we create an **organization**, **group** or **resource** with fluent extension enabled the default `note/description` field is `null` . it should be the same as english value for that field.
2. The **org_title** and **group_title** on top nav is displaying the name instead of title. This is because display_name being set as the name value.  This should be fixed

![image](https://user-images.githubusercontent.com/60897650/153016540-1902ba46-ba28-4263-b969-3b1c2cf3d296.png)
![image](https://user-images.githubusercontent.com/60897650/153016608-f01985cc-5c2d-494f-8b02-ec1213991902.png)

## Acceptance

* [x] Default description/notes is not null for
  * [x] Organizations
    * [x] Default description is same as notes_translated (english)
    * [x] Display name is same as english title
  * [x] Group
    * [x] Default description is same as notes_translated (english)
    * [x] Display name is same as english title 
  * [x] Resource 

## Tasks
* [x] Push the english description as the default description of the org/group/resource.
* [x] Fix the display name issue for organisations and groups
  ![Screenshot from 2022-02-08 18-59-49](https://user-images.githubusercontent.com/57398621/153002618-18adf590-e7b3-40f2-ba83-a6587f49095b.png)
  ![Screenshot from 2022-02-08 18-56-16](https://user-images.githubusercontent.com/57398621/153002622-5de17f33-ca7f-45a9-a7ed-fac398dd853c.png)
* [x] Test and validate

**Comment by osahon-okungbowa** [comment]
@sagargg i have updated the ticket. Please start on this first thing tomorrow morning as agreed. 
thank you

**Comment by sagargg** [comment]
Thanks, @osahon-okungbowa. I already raised PR for this https://github.com/FCSCOpendata/ckanext-fcscopendata/pull/9. 
I believe it will fix all the issues mentioned above.

**Comment by osahon-okungbowa** [comment]
@sagargg i was thinking you would want to update the description of the ticket and include the "Organisation" and "GRoup" About Page bug. i mentioned today.
But if you prefer to create a new issue for that bug, we can close it. Let me know, what you decide

**Comment by sagargg** [comment]
@osahon-okungbowa  I almost forgot that part.  I will create the new issue and work tomorrow on that.

**Comment by sagargg** [comment]
closing as FIXED.
