### ISSUE TITLE
 Internal server error on dataset creation

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#80]
The client is reporting the internal server error on dataset creation. 

## Tasks
* [ ] Investigate  the issue. 
* [ ] Fix and deploy and test. 
* [x] Update the client regarding fix. 

Fond below Errors in log
``` python
2022-07-04 09:30:09,516 ERROR [ckan.config.middleware.flask_app] unconverted data remains: -01
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/srv/app/src/ckan/ckan/config/middleware/../../views/dataset.py", line 592, in post
    pkg_dict = get_action(u'package_create')(context, data_dict)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckanext-datasetapproval/ckanext/datasetapproval/actions.py", line 35, in package_create
    dataset_dict = up_func(context, data_dict)
  File "/srv/app/src/ckanext-fcscopendata/ckanext/fcscopendata/logic/action/create.py", line 31, in package_create
    start_date = datetime.strptime(str(start_period), '%Y-%m').isoformat()
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: -01
```
