### ISSUE TITLE
Fix bug and install ckanext-rating extension on dev environment. 

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#87]
## Acceptance Criteria
* [ ] I fixed the bug on`ckanext-rating` extension and deployed it to the dev env. 

## Tasks 
* [x] Fix font awesome issue(bug) on [ckanext-rating](https://github.com/6aika/ckanext-rating). 
* [x] Fork ckanext-rating to datopian organization and push bug fix changes there. 
* [ ] Review/Test/Deploy

**Comment by sagargg** [comment]
Forked repo and create a new tag for `ckan-2.9`. https://github.com/datopian/ckanext-rating/tree/ckan-2.9

## Installation steps
To install this extension to FCSC dev env, 
- Add `rating` plugin before FCSC extension.
- Run this command to initialize the required database table . `ckan --config=ckan.ini rating init`
- Also add `rating.enabled_for_unauthenticated_users = true` env variable to allow submit rating for unauthenticated users.

## API Documentation 
1. To submit the rating to the dataset.
```
curl --location --request POST 'https://ckan.fcsc.develop.datopian.com/api/3/action/rating_package_create' \
--header 'Content-Type: application/json' \
--data-raw '{
    "package": "f0ca8028-88f6-49a3-a45f-c9012ac27c82",
    "rating": "1"
}'
```

2. To retrieve the rating result of the dataset.
```
curl --location --request POST 'https://ckan.fcsc.develop.datopian.com/api/3/action/rating_package_get' \
--header 'Content-Type: application/json' \
--data-raw '{
    "package_id": "f0ca8028-88f6-49a3-a45f-c9012ac27c82"
}'
```

**Comment by sagargg** [comment]
**FIXED**
