### ISSUE TITLE
Bilingual support for tags

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/ckanext-fcscopendata#89]
As an arabic user, I'd like to be able to see all the CKAN objects in Arabic, including tags, so that I can make use of the website in my native language.
  
## Acceptance Criteria: 
- [ ] I can see an investigation/results provided for this issue
  
## Tasks:
- [ ] Investigate the technical difficulties of adding the `title_translated` field to the tags field of `package_search`, as this is the endpoint used for pulling the tags that are displayed in the homepage of the frontend app (note: this same endpoint is also used for the dataset page)
- [ ] If decided to not implement the field, come up with alternatives for this
