### ISSUE TITLE
[Support] Organization logo not uploading correctly

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/ckanext-fcscopendata#98]
## Description

After uploading a logo for the UAEU organization, it was noticed that the logo wasn't showing up on the front end:

![image](https://github.com/FCSCOpendata/ckanext-fcscopendata/assets/16550934/5a439e65-74b0-416e-8745-f703a6ff8b15)

The logo can be found on the notes section below 

## Acceptance Criteria

- [ ] The logo for the UAEU is uploading correctly and showing up on the front end

## Tasks

- [x] Investigate the issue
- [x] Find a solution **:white_check_mark: After trying to upload the logo again it worked. Our recommendation is to simply retry uploading the image when it fails**
- [x] Notify the FCSC team

### Logo

![UAEU-1](https://github.com/FCSCOpendata/ckanext-fcscopendata/assets/16550934/6639d573-32f3-437a-9a7c-f86ebd1ee068)

**Comment by osahon-okungbowa** [comment]
Marking this as resolved and closing.

Client never responded to request for confirmation so we assume this was resolved
